export const TODAYSUBSCRIPTION = "TODAYSUBSCRIPTION"

export const ALLSUBSCRIPTION = "ALLSUBSCRIPTION"

export const TRIAL = "TRIAL"

export const SUBSCRIPTION_STARTLOADING  = "SUBSCRIPTION_STARTLOADING";

export  const SUBSCRIPTION_SHOWNOTIFICATION = "SUBSCRIPTION_SHOWNOTIFICATION"
 
export const CURRENTMONTHSUBSCRIPTION="CURRENTMONTHSUBSCRIPTION"

export const EXPIRINGSUBSCRIPTION = "EXPIRINGSUBSCRIPTION"