 export const GETSTRATEGIES =  "GETSTRATEGIES";
 export const STRATEGIESLASTTENTRADS  = "STRATEGIESLASTTENTRADS"
 export const EDIT_STRATEGIES_STATUS  = "EDIT_STRATEGIES_STATUS"

 export const STRATEGIES_STARTLOADING =  "STRATEGIES_STARTLOADING"
 export const STRATEGIES_SHOWNOTIFICATION = "STRATEGIES_SHOWNOTICATION"
 export const STRATEGIES_STOPLOADING  =  "STRATEGIES_STOPLOADING"