export const SUBSCRIPTIONDETAIL =  "SUBSCRIPTIONDETAIL"

export const SUBSCRIPTIONDETAIL_STARTLOADING  =  "SUBSCRIPTIONDETAIL_STARTLOADING"

export const SUBSCRIPTIONDETAIL_SHOWNOTIFICATION = "SUBSCRIPTIONDETAIL_SHOWNOTIFICATION"

