export const RUNNINGTRADES="RUNNINGTRADES"

export const TODAYSORDERS="TODAYSORDERS"

export const VIEWORDERS="VIEWORDERS"

 
export const TRADES_STARTLOADING  = "TRADES_STARTLOADING"

export const TRADES_SHOWNOTIFICATION =  "TRADES_SHOWNOTIFICATION"

export const TRADES_SHOW_SUCCESS_NOTIFICATION =  "TRADES_SHOW_SUCCESS_NOTIFICATION"

 
export const PLACEORDER="PLACEORDER"
 
export const TRADEDUSERS="TRADEDUSERS"

export const USERWISE_TRADES = "USERWISE_TRADES"

export const GETRUNNINGEQUITYTRADES = "GETRUNNINGEQUITYTRADES"