export const USERCOUNT = "USERCOUNT"

export const ACTIVEBOTS = "ACTIVEBOTS"

export const USER_STARTLOADING =  "USER_STARTLOADING"

export const USER_SHOWNOTIFICATION  = "USER_SHOWNOTIFACTION"

export const ALLOWED_STRATEGIES = "ALLOWED_STRATEGIES"