export const GET_CLIENT_DETAIL  = "GET_CLIENT_DETAIL"
export const GET_CLIENT_STRATEGIES_DETAIL =  "GET_CLIENT_STRATEGIES_DETAIL"
export const UPDATE_CLIENT_DETAIL_BROKER = "UPDATE_CLIENT_DETAIL_BROKER"

export const CLIENT_DETAIL_STARTLOADING = "CLIENT_DETAIL_STARTLOADING"

export  const  CLIENT_DETAIL_SHOWNOTIFICATION = "CLIENT_DETAIL_SHOWNOTIFICATION" 
